spring:
    application:
        name: personle-api
    mvc:
        throw-exception-if-no-handler-found: true
    resources:
        add-mappings: false

server:
    error:
        whitelabel:
            enabled: false

aws:
    region: us-east-2
    s3:
        dailyPersonas:
            bucketName: daily-personas
    dynamodb:
        userGameData:
            tableName: UserGameData