spring:
    application:
        name: personle-api

aws:
    region: us-east-2
    s3:
        dailyPersonas:
            bucketName: daily-personas
    dynamodb:
        userGameData:
            tableName: UserGameData